### ISSUE TITLE
Lack of function 'spikes2sawtooth.m'

### ISSUE THREAD

**Issue by shihan-ma** [smetanadvorak/iemg_simulator#2]
Thanks for your share.

It seems that there is no function 'spikes2sawtooth.m' ('MuscleForceMdl.m'[121]). Thus, the following codes can not be run.

Hope that you can solve this problem. Thanks!

**Comment by anilthota** [comment]
Any updates on the function spikes2sawtooth.m? I ran into same problem.
Thanks

**Comment by shihan-ma** [comment]
Hi Anil,

I'm sorry that I haven't figured out the problem about the function 'spikes2sawtooth.m'. Actually the first two scripts ('s1_cl_init_mn_pool.m' and 's1_cl_init_mu_pool') are enough for us since we are only interested in the distribution of muscle fibers and motor neurons.

Hope that you can get it solved soon.

Best regards,
Shihan

----- 原始邮件 -----
发件人: "anilthota" <notifications@github.com>
收件人: "smetanadvorak/iemg_simulator" <iemg_simulator@noreply.github.com>
抄送: "Shihan" <mmasss@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期五, 2020年 4 月 03日 上午 5:33:51
主题: Re: [smetanadvorak/iemg_simulator] Lack of function 'spikes2sawtooth.m' (#2)

Any updates on the function spikes2sawtooth.m? I ran into same problem.
Thanks

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/smetanadvorak/iemg_simulator/issues/2#issuecomment-608102072
--

**Comment by smetanadvorak** [comment]
Dear @Shihan-SJTU and @anilthota 
I added the missing functions to the repository. Testing on my computer doesn't throw any errors. Please consider testing the latest commit.
